// CloudVPN Worker — VLESS/WS proxy
// Auto-generated by CloudVPN Deploy Platform
const uuid = (env.UUID || 'd342d11e-d424-4583-b36e-524ab1c88aa6').toLowerCase();
const proxyIPs = (env.PROXYIP || '').split(',').map(s => s.trim()).filter(Boolean);
const cleanIPs = (env.CLEANIP || '').split(',').map(s => s.trim()).filter(Boolean);
const port = parseInt(env.PORT || '443', 10);
const sni = env.SNI || '';
const host = env.HOST || '';

export default {
  async fetch(request, env) {
    const url = new URL(request.url);
    const upgrade = request.headers.get('Upgrade');
    if (upgrade !== 'websocket') {
      return new Response(JSON.stringify({ ok: true, service: 'cloudvpn-worker' }), {
        headers: { 'Content-Type': 'application/json' },
      });
    }
    // VLESS WebSocket handler stub
    const pair = new WebSocketPair();
    return new Response(null, { status: 101, webSocket: pair[1] });
  },
};
